name: HOTS3D
channels:
  - pytorch3d
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=openblas
  - brotli-python=1.0.9
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - idna=3.7
  - ld_impl_linux-64=2.40
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libopenblas=0.3.21
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=1.1.1w
  - pip=24.2
  - pysocks=1.7.1
  - python=3.10.0
  - pytorch3d=0.7.4
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tqdm=4.66.5
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
 
  - pip:
    - git+https://github.com/openai/CLIP.git@main
    - git+https://github.com/openai/shap-e.git@main
    - absl-py==2.1.0
    - addict==2.4.0
    - asttokens==2.4.1
    - attrs==25.3.0
    - blinker==1.9.0
    - blobfile==3.0.0
    - chardet==5.2.0
    - click==8.1.8
    - comm==0.2.2
    - configargparse==1.7
    - contourpy==1.3.0
    - cycler==0.12.1
    - dash==3.0.1
    - decorator==5.1.1
    - diffusers==0.32.2
    - exceptiongroup==1.2.2
    - executing==2.1.0
    - fastjsonschema==2.21.1
    - filelock==3.16.1
    - flask==3.0.3
    - fonttools==4.56.0
    - fsspec==2025.2.0
    - ftfy==6.3.0
    - grpcio==1.70.0
    - h5py==3.12.1
    - huggingface-hub==0.29.2
    - humanize==4.11.0
    - ipython==8.18.1
    - ipywidgets==8.1.5
    - itsdangerous==2.2.0
    - jedi==0.19.1
    - jinja2==3.1.6
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - jupyter-core==5.7.2
    - jupyterlab-widgets==3.0.13
    - kiwisolver==1.4.7
    - light-field-distance==0.0.9
    - lxml==5.3.0
    - markdown==3.7
    - markupsafe==3.0.2
    - matplotlib==3.9.4
    - matplotlib-inline==0.1.7
    - narwhals==1.33.0
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - pandas==2.1.4
    - parso==0.8.4
    - pexpect==4.9.0
    - pillow==10.4.0
    - plotly==6.0.1
    - prompt-toolkit==3.0.48
    - protobuf==5.29.3
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pycryptodomex==3.21.0
    - pygments==2.18.0
    - pyparsing==3.2.3
    - pyquaternion==0.9.9
    - python-dateutil==2.9.0.post0
    - pytz==2024.2
    - pyyaml==6.0.2
    - referencing==0.36.2
    - regex==2024.9.11
    - retrying==1.3.4
    - rpds-py==0.24.0
    - safetensors==0.5.3
    - scikit-learn==1.4.2
    - scipy==1.13.1
    - six==1.16.0
    - stack-data==0.6.3
    - tensorboard==2.18.0
    - tensorboard-data-server==0.7.2
    - termcolor==2.5.0
    - threadpoolctl==3.5.0
    - tokenizers==0.21.0
    - traitlets==5.14.3
    - transformers==4.49.0
    - trimesh==4.5.0
    - typing-extensions==4.12.2
    - tzdata==2024.2
    - wcwidth==0.2.13
    - werkzeug==3.0.3
    - widgetsnbextension==4.0.13

